# This file sets control variables for the internal control mechanisms in the actuators and 
# settings used throughout the driver.
# 
# It is **NOT** recommended to edit these values by hand.
# Parmeter changes, especially to PID, can cause unexpected behavior that poses a risk to the 
# robot and its environment.
#
# Don't do it!
#

1:
    p: 800
    i: 0
    d: 6000
    acceleration: 10
    velocity: 200
    gr: 4
    mode: 5
2:
    p: 800
    i: 0
    d: 6000
    acceleration: 20
    velocity: 400
    gr: 6
    mode: 5
3:
    p: 800
    i: 0
    d: 6000
    acceleration: 20
    velocity: 400
    gr: 6
    mode: 5
4:
    p: 2000
    i: 0
    d: 10000
    acceleration: 10
    velocity: 100
    gr: 1
    mode: 5
5:
    p: 800
    i: 0
    d: 6000
    acceleration: 5
    velocity: 100
    gr: 4
    mode: 5
6:
    p: 400
    i: 0
    d: 3000
    acceleration: 5
    velocity: 100
    gr: 1
    mode: 3
7:
    p: 500
    i: 0
    d: 900
    acceleration: 10
    velocity: 80
    gr: 1
    mode: 0

